# Generated by Selenium IDE
import time

import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait


class TestSearchInput:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_search_input(self):
        self.driver.get("https://smi2.ru/")
        self.driver.set_window_size(1944, 1070)
        
        WebDriverWait(self.driver, 15).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "body"))
        )
        
        search_input = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, "input[name='search']"))
        )
        
        search_input.send_keys("Путин")
        
        search_button = self.driver.find_element(By.CSS_SELECTOR, "button[class*='Filter_searchBtnSvg']")
        search_button.click()
        
        WebDriverWait(self.driver, 10).until(
            lambda d: d.execute_script("return document.readyState") == "complete"
        )
        
        print("Search performed for: Путин")