# Generated by Selenium IDE
import json
import time

import pytest
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait


class TestButtonstopnegativeworks:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_buttonstopnegativeworks(self):
        self.driver.get("https://smi2.ru/")
        self.driver.set_window_size(1944, 1070)

        try:
            WebDriverWait(self.driver, 15).until(
                EC.invisibility_of_element_located((By.XPATH, "(//template)[1]"))
                # OR if it was specifically under body:
                # EC.invisibility_of_element_located((By.XPATH, "//body/template"))
            )
        except Exception:
            pass  # If it's already gone, this might timeout or pass depending on implementation.
            # Better to use staleness_of if you captured the element first.

        # 2. NOW wait for your actual button to be clickable
        toggle_btn = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable(
                (By.CSS_SELECTOR, "div[class^='GoodFeedToggle_sourceToggleSwitcher']")
            )
        )

        news_container = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable(
                (
                    By.CSS_SELECTOR,
                    "section[class^='ArticlesFeedWrapper_newsContLine'] > div",
                )
            )
        )
        children_before = len(news_container.find_elements(By.XPATH, "./*"))

        print(f"Children before: {children_before}")

        toggle_parent = toggle_btn.find_element(By.XPATH, "..")

        old_class = toggle_parent.get_attribute("class")
        toggle_btn.click()
        new_class = toggle_parent.get_attribute("class")

        assert old_class != new_class

        parent_container_after = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable(
                (
                    By.CSS_SELECTOR,
                    "section[class^='ArticlesFeedWrapper_newsContLine'] > div",
                )
            )
        )

        children_after = len(parent_container_after.find_elements(By.XPATH, "./*"))

        print(f"Children after: {children_after}")

        assert children_after < children_before, (
            f"Expected fewer children, but before={children_before}, after={children_after}"
        )

        # revert to how it was before
        toggle_btn.click()
